#!/bin/bash

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
  vim +PluginInstall +qa
fi

# get bash-it up and running
cd "$(dirname "$0")"
git submodule update --init

